import Head from "next/head";
import SideBar from "@/components/navigation/SideBar";
import Footer from "@/components/navigation/Footer";

export default function DefaultLayout({ children, title }: any) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favico.png" />
      </Head>
      <SideBar>{children}</SideBar>
      <Footer />
    </>
  );
}
