import Head from "next/head";
import SideBar from "@/components/navigation/SideBar";
import Footer from "@/components/navigation/Footer";
import { useAuth } from "@/contexts/auth";
import { useEffect, useState } from "react";
import axios from "axios";
import { UserContext } from "@/contexts/UserContext";

type User = {
  id: number;
  username: string;
  email: string;
  personal_data: any;
  created_at: string;
  updated_at: string;
};

export default function DefaultLayout({ children, title }: any) {
  const apiURL = process.env.API_ENDPOINT;
  const { token, userId } = useAuth();
  // States
  const [user, setUser] = useState<User | null>(null);

  useEffect(() => {
    const fetchLoggedInUser = async () => {
      try {
        const res = await axios.get(`${apiURL}/users/${userId}`, {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });

        if (res.status === 404) {
          return {
            notFound: true,
          };
        }

        setUser(res.data);
      } catch (error) {
        console.log(error);
      }
    };
    fetchLoggedInUser();
  }, [apiURL, token, userId]);

  return (
    <UserContext.Provider value={{ user, setUser }}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar>{children}</SideBar>
      <Footer />
    </UserContext.Provider>
  );
}
